package prodottosistema;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;
public class TestAggiuntaAlCarrelloTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "test/acquistosistema/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testAggiuntaAlCarrelloProdottoNonDisponibile() {
    // Test name: TestAggiuntaAlCarrello_ProdottoNonDisponibile
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletprodotto?id=2 | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletprodotto?id=2");
    // 2 | click | css=.pl-2 | 
    driver.findElement(By.cssSelector(".pl-2")).click();
    // 3 | assertAlert | Prodotto non disponibile in magazzino | 
    assertThat(driver.switchTo().alert().getText(), is("Prodotto non disponibile in magazzino"));
  }
  @Test
  public void testAggiuntaAlCarrelloProdottoGiaAggiunto() {
    // Test name: TestAggiuntaAlCarrello_ProdottoGiaAggiunto
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletprodotto?id=1 | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletprodotto?id=1");
    // 2 | setWindowSize | 1366x728 | 
    driver.manage().window().setSize(new Dimension(1366, 728));
    // 3 | click | css=.fa-shopping-cart | 
    driver.findElement(By.cssSelector(".fa-shopping-cart")).click();
    // 4 | assertAlert | Hai gia questo prodotto nell carrello | 
    assertThat(driver.switchTo().alert().getText(), is("Hai gia questo prodotto nell carrello"));
  }
  @Test
  public void testAggiuntaAlCarrelloProdottoAggiunto() {
    // Test name: TestAggiuntaAlCarrello_ProdottoAggiunto
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletprodotto?id=1 | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletprodotto?id=1");
    // 2 | click | css=.pl-2 | 
    driver.findElement(By.cssSelector(".pl-2")).click();
    // 3 | assertAlert | Aggiunta nel carrello fatta con successo! | 
    assertThat(driver.switchTo().alert().getText(), is("Aggiunta nel carrello fatta con successo!"));
  }
}
