package prodottosistema;

//Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.SessionId;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestRifornituraProdotto{
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;
	
	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "test/prodottosistema/chromedriver");
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}
	
	@After
	public void tearDown() {
		driver.quit();
	}
	
	@Test
	public void testRifornituraProdottoOK() {
		driver.get("http://localhost:8080/RAAF-GAMING/servletaccessoadmin");
	    driver.manage().window().setSize(new Dimension(1050, 616));
	    driver.findElement(By.id("exampleInputEmail1")).click();
	    driver.findElement(By.id("exampleInputEmail1")).sendKeys("prodotto@admin.com");
	    driver.findElement(By.id("exampleInputPassword1")).sendKeys("veloce123");
	    driver.findElement(By.id("exampleInputPassword1")).sendKeys(Keys.ENTER);
		 // Test name: testRifornituraProdottoOK
		 
		 // 2 | setWindowSize | 1050x616 |  | 
		 driver.manage().window().setSize(new Dimension(1050, 616));
		 // 3 | click | css=.form-row > label:nth-child(2) |  | 
		 driver.findElement(By.cssSelector(".form-row > label:nth-child(2)")).click();
		 // 4 | click | name=quantita |  | 
		 driver.findElement(By.name("quantita")).click();
		 // 5 | type | name=quantita | 1 | 
		 driver.findElement(By.name("quantita")).sendKeys("1");
		 // 6 | click | css=#idrow0 .btn |  | 
		 driver.findElement(By.cssSelector("#idrow0 .btn")).click();
		 // 7 | assertText | name=successo | Prodotto Rifornito con Successo | 
		 assertEquals(driver.findElement(By.name("successo")).getText(), "Prodotto Rifornito con Successo");
	}
	
	@Test
	public void testRifornituraProdottoQuantitaNo() {
	 // Test name: testRifornituraProdottoQuantitaNo
		driver.get("http://localhost:8080/RAAF-GAMING/servletaccessoadmin");
	    driver.manage().window().setSize(new Dimension(1050, 616));
	    driver.findElement(By.id("exampleInputEmail1")).click();
	    driver.findElement(By.id("exampleInputEmail1")).sendKeys("prodotto@admin.com");
	    driver.findElement(By.id("exampleInputPassword1")).sendKeys("veloce123");
	    driver.findElement(By.id("exampleInputPassword1")).sendKeys(Keys.ENTER);
	 // 2 | click | css=.form-row > label:nth-child(2) |  | 
	 driver.findElement(By.cssSelector(".form-row > label:nth-child(2)")).click();
	 // 3 | click | name=quantita |  | 
	 driver.findElement(By.name("quantita")).click();
	 // 4 | type | name=quantita | -20 | 
	 driver.findElement(By.name("quantita")).sendKeys("-20");
	 // 5 | click | css=#idrow0 .btn |  | 
	 driver.findElement(By.cssSelector("#idrow0 .btn")).click();
	 // 6 | assertElementNotPresent | name=successo |  | 
	 {
	   List<WebElement> elements = driver.findElements(By.name("successo"));
	   assert(elements.size() == 0);
	 }
	 // 7 | assertElementNotPresent | name=errore |  | 
	 {
	   List<WebElement> elements = driver.findElements(By.name("errore"));
	   assert(elements.size() == 0);
	 }
	}
	
	@Test
	public void testRifornituraProdottoCapienzaNO() {
	 // Test name: testRifornituraProdottoCapienzaNO
		driver.get("http://localhost:8080/RAAF-GAMING/servletaccessoadmin");
	    driver.manage().window().setSize(new Dimension(1050, 616));
	    driver.findElement(By.id("exampleInputEmail1")).click();
	    driver.findElement(By.id("exampleInputEmail1")).sendKeys("prodotto@admin.com");
	    driver.findElement(By.id("exampleInputPassword1")).sendKeys("veloce123");
	    driver.findElement(By.id("exampleInputPassword1")).sendKeys(Keys.ENTER);
	 // 2 | setWindowSize | 1050x616 |  | 
	 driver.manage().window().setSize(new Dimension(1050, 616));
	 // 3 | click | css=.form-row > label:nth-child(2) |  | 
	 driver.findElement(By.cssSelector(".form-row > label:nth-child(2)")).click();
	 // 4 | click | css=#idrow1 > td > input |  | 
	 driver.findElement(By.cssSelector("#idrow1 > td > input")).click();
	 // 5 | type | css=#idrow1 > td > input | 5000 | 
	 driver.findElement(By.cssSelector("#idrow1 > td > input")).sendKeys("5000");
	 // 6 | click | css=#idrow1 .btn |  | 
	 driver.findElement(By.cssSelector("#idrow1 .btn")).click();
	 // 7 | assertElementPresent | name=errore |  | 
	 {
	   List<WebElement> elements = driver.findElements(By.name("errore"));
	   assert(elements.size() > 0);
	 }
	 // 8 | assertText | name=errore | Capienza non disponibile | 
	 assertEquals(driver.findElement(By.name("errore")).getText(), "Capienza non disponibile");
	}
	
}