package prodottosistema;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class VisualizzaOrdineTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "test/acquistosistema/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void visualizzaOrdine() throws InterruptedException {
    // Test name: VisualizzaOrdine
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletloginfirst | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletloginfirst");
    Thread.sleep(2500);
    // 2 | setWindowSize | 1936x1056 | 
    driver.manage().window().setSize(new Dimension(1936, 1056));
    Thread.sleep(2500);
    // 3 | click | name=email | 
    driver.findElement(By.name("email")).click();
    Thread.sleep(2500);
    // 4 | type | name=email | f.peluso25@gmail.com
    driver.findElement(By.name("email")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(2500);
    // 5 | click | name=password | 
    driver.findElement(By.name("password")).click();
    Thread.sleep(2500);
    // 6 | type | name=password | veloce123
    driver.findElement(By.name("password")).sendKeys("veloce123");
    Thread.sleep(2500);
    // 7 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    Thread.sleep(2500);
    // 8 | click | id=dropdownMenuButton | 
    driver.findElement(By.id("dropdownMenuButton")).click();
    Thread.sleep(2500);
    // 9 | click | linkText=I miei ordini | 
    driver.findElement(By.linkText("I miei ordini")).click();
    Thread.sleep(2500);
    // 10 | assertText | id=peppino | I TUOI ORDINI
    assertThat(driver.findElement(By.id("peppino")).getText(), is("I TUOI ORDINI"));
  }
}
