package profilosistema;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestProfilo {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "test/profilosistema/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testProfiloEseguito() throws InterruptedException {
    // Test name: TestProfiloEseguito
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletloginfirst |  | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletloginfirst");
    Thread.sleep(2000);
    // 2 | click | name=email |  | 
    driver.findElement(By.name("email")).click();
    Thread.sleep(2000);
    // 3 | type | name=email | f.peluso25@gmail.com | 
    driver.findElement(By.name("email")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(2000);
    // 4 | click | name=password |  | 
    driver.findElement(By.name("password")).click();
    Thread.sleep(2000);
    // 5 | type | name=password | veloce123 | 
    driver.findElement(By.name("password")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 6 | click | css=.invio |  | 
    driver.findElement(By.cssSelector(".invio")).click();
    Thread.sleep(2000);
    // 7 | click | css=.fa-user-astronaut |  | 
    driver.findElement(By.cssSelector(".fa-user-astronaut")).click();
    Thread.sleep(2000);
    // 8 | click | linkText=Profilo |  | 
    driver.findElement(By.linkText("Profilo")).click();
    Thread.sleep(2000);
    // 9 | click | id=inputPassword1 |  | 
    driver.findElement(By.id("inputPassword1")).click();
    Thread.sleep(2000);
    // 10 | type | id=inputPassword1 | veloce1234 | 
    driver.findElement(By.id("inputPassword1")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 11 | click | id=inputPassword2 |  | 
    driver.findElement(By.id("inputPassword2")).click();
    Thread.sleep(2000);
    // 12 | type | id=inputPassword2 | veloce1234 | 
    driver.findElement(By.id("inputPassword2")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 13 | click | id=inputCarta1 |  | 
    driver.findElement(By.id("inputCarta1")).click();
    Thread.sleep(2000);
    // 14 | type | id=inputCarta1 | 1234567899898989 | 
    driver.findElement(By.id("inputCarta1")).sendKeys("1234567899898989");
    Thread.sleep(2000);
    // 15 | click | id=inputCarta2 |  | 
    driver.findElement(By.id("inputCarta2")).click();
    Thread.sleep(2000);
    // 16 | type | id=inputCarta2 | 123 | 
    driver.findElement(By.id("inputCarta2")).sendKeys("123");
    Thread.sleep(2000);
    // 17 | click | id=inputCarta3 |  | 
    driver.findElement(By.id("inputCarta3")).click();
    Thread.sleep(2000);
    // 18 | type | id=inputCarta3 | 2022-02-05 | 
    driver.findElement(By.id("inputCarta3")).sendKeys("05/04/2023");
    Thread.sleep(2000);
    // 19 | click | css=.btn-primary |  | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    Thread.sleep(2000);
    // 20 | assertText | id=notifica | PASSWORD MODIFICATA! | 
    assertThat(driver.findElement(By.id("notifica")).getText(), is("PASSWORD MODIFICATA!"));
    Thread.sleep(2000);
    // 21 | assertText | name=codicecartaselenium | *****8989 | 
    assertThat(driver.findElement(By.name("codicecartaselenium")).getText(), is("*****8989"));
    Thread.sleep(2000);
  }
  
  @Test
  public void testProfiloErroreCarta() throws InterruptedException {
    // Test name: TestProfiloErroreCarta
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletloginfirst | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletloginfirst");
    Thread.sleep(2000);
    // 2 | click | name=email | 
    driver.findElement(By.name("email")).click();
    Thread.sleep(2000);
    // 3 | type | name=email | f.peluso25@gmail.com
    driver.findElement(By.name("email")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(2000);
    // 4 | click | name=password | 
    driver.findElement(By.name("password")).click();
    Thread.sleep(2000);
    // 5 | type | name=password | veloce123
    driver.findElement(By.name("password")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 6 | sendKeys | name=password | ${KEY_ENTER}
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    Thread.sleep(2000);
    // 7 | click | id=dropdownMenuButton | 
    driver.findElement(By.id("dropdownMenuButton")).click();
    Thread.sleep(2000);
    // 8 | click | linkText=Profilo | 
    driver.findElement(By.linkText("Profilo")).click();
    Thread.sleep(2000);
    // 9 | click | id=inputPassword1 | 
    driver.findElement(By.id("inputPassword1")).click();
    Thread.sleep(2000);
    // 10 | type | id=inputPassword1 | veloce1234
    driver.findElement(By.id("inputPassword1")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 11 | click | id=inputPassword2 | 
    driver.findElement(By.id("inputPassword2")).click();
    Thread.sleep(2000);
    // 12 | type | id=inputPassword2 | veloce1234
    driver.findElement(By.id("inputPassword2")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 13 | click | id=inputCarta1 | 
    driver.findElement(By.id("inputCarta1")).click();
    Thread.sleep(2000);
    // 14 | type | id=inputCarta1 | 1
    driver.findElement(By.id("inputCarta1")).sendKeys("1");
    Thread.sleep(2000);
    // 15 | click | id=inputCarta2 | 
    driver.findElement(By.id("inputCarta2")).click();
    Thread.sleep(2000);
    // 16 | type | id=inputCarta2 | 123
    driver.findElement(By.id("inputCarta2")).sendKeys("123");
    Thread.sleep(2000);
    // 17 | click | id=inputCarta3 | 
    driver.findElement(By.id("inputCarta3")).click();
    Thread.sleep(2000);
    // 18 | click | id=inputCarta3 | 
    driver.findElement(By.id("inputCarta3")).click();
    Thread.sleep(2000);
    // 19 | type | id=inputCarta3 | 2022-02-04
    driver.findElement(By.id("inputCarta3")).sendKeys("04/02/2023");
    Thread.sleep(2000);
    // 20 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    Thread.sleep(2000);
    // 21 | assertAlert | Hai inserito una carta non valida | 
    assertThat(driver.switchTo().alert().getText(), is("Hai inserito una carta non valida"));
    Thread.sleep(2000);
  }
  
  
  @Test
  public void testProfiloErrorePWD() throws InterruptedException {
    // Test name: TestProfiloErrorePWD
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletloginfirst | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletloginfirst");
    Thread.sleep(2000);
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    //Thread.sleep(2000);
    // 3 | click | name=email | 
    driver.findElement(By.name("email")).click();
    Thread.sleep(2000);
    // 4 | type | name=email | f.peluso25@gmail.com
    driver.findElement(By.name("email")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(2000);
    // 5 | click | name=password | 
    driver.findElement(By.name("password")).click();
    Thread.sleep(2000);
    // 6 | type | name=password | veloce123
    driver.findElement(By.name("password")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 7 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    Thread.sleep(2000);
    // 8 | click | css=.fa-user-astronaut | 
    driver.findElement(By.cssSelector(".fa-user-astronaut")).click();
    Thread.sleep(2000);
    // 9 | click | linkText=Profilo | 
    driver.findElement(By.linkText("Profilo")).click();
    Thread.sleep(2000);
    // 10 | click | id=inputPassword1 | 
    driver.findElement(By.id("inputPassword1")).click();
    Thread.sleep(2000);
    // 11 | type | id=inputPassword1 | ab1
    driver.findElement(By.id("inputPassword1")).sendKeys("ab1");
    Thread.sleep(2000);
    // 12 | click | id=inputPassword2 | 
    driver.findElement(By.id("inputPassword2")).click();
    Thread.sleep(2000);
    // 13 | type | id=inputPassword2 | ab1
    driver.findElement(By.id("inputPassword2")).sendKeys("ab1");
    Thread.sleep(2000);
    // 14 | click | id=inputCarta1 | 
    driver.findElement(By.id("inputCarta1")).click();
    Thread.sleep(2000);
    // 15 | type | id=inputCarta1 | 1234567899898989
    driver.findElement(By.id("inputCarta1")).sendKeys("1234567899898989");
    Thread.sleep(2000);
    // 16 | click | id=inputCarta2 | 
    driver.findElement(By.id("inputCarta2")).click();
    Thread.sleep(2000);
    // 17 | type | id=inputCarta2 | 123
    driver.findElement(By.id("inputCarta2")).sendKeys("123");
    Thread.sleep(2000);
    // 18 | click | id=inputCarta3 | 
    driver.findElement(By.id("inputCarta3")).click();
    Thread.sleep(2000);
    // 19 | type | id=inputCarta3 | 2022-02-05
    driver.findElement(By.id("inputCarta3")).sendKeys("05/02/2022");
    Thread.sleep(2000);
    // 20 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    Thread.sleep(3000);
    // 21 | assertAlert | password non valida | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    System.out.println(str);
    assertEquals("password non valida",str);
    alert.accept();
    Thread.sleep(2000);
    // 22 | assertText | name=codicecartaselenium | *****8989
    assertThat(driver.findElement(By.name("codicecartaselenium")).getText(), is("*****8989"));
  }
  
  
  @Test
  public void testProfiloErroreData() throws InterruptedException {
    // Test name: TestProfiloErroreData
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletloginfirst | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletloginfirst");
    Thread.sleep(2000);
    // 2 | click | name=email | 
    driver.findElement(By.name("email")).click();
    Thread.sleep(2000);
    // 3 | type | name=email | f.peluso25@gmail.com
    driver.findElement(By.name("email")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(2000);
    // 4 | click | name=password | 
    driver.findElement(By.name("password")).click();
    Thread.sleep(2000);
    // 5 | type | name=password | veloce123
    driver.findElement(By.name("password")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 6 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    Thread.sleep(2000);
    // 7 | click | css=.fa-user-astronaut | 
    driver.findElement(By.cssSelector(".fa-user-astronaut")).click();
    Thread.sleep(2000);
    // 8 | click | linkText=Profilo | 
    driver.findElement(By.linkText("Profilo")).click();
    Thread.sleep(2000);
    // 9 | click | id=inputPassword1 | 
    driver.findElement(By.id("inputPassword1")).click();
    Thread.sleep(2000);
    // 10 | type | id=inputPassword1 | veloce1234
    driver.findElement(By.id("inputPassword1")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 11 | click | id=inputPassword2 | 
    driver.findElement(By.id("inputPassword2")).click();
    Thread.sleep(2000);
    // 12 | type | id=inputPassword2 | veloce1234
    driver.findElement(By.id("inputPassword2")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 13 | click | id=inputCarta1 | 
    driver.findElement(By.id("inputCarta1")).click();
    Thread.sleep(2000);
    // 14 | type | id=inputCarta1 | 1234567898989898
    driver.findElement(By.id("inputCarta1")).sendKeys("1234567898989898");
    Thread.sleep(2000);
    // 15 | click | id=inputCarta2 | 
    driver.findElement(By.id("inputCarta2")).click();
    Thread.sleep(2000);
    // 16 | type | id=inputCarta2 | 123
    driver.findElement(By.id("inputCarta2")).sendKeys("123");
    Thread.sleep(2000);
    // 17 | click | id=inputCarta3 | 
   // driver.findElement(By.id("inputCarta3")).click();
    //Thread.sleep(2000);
    // 18 | type | id=inputCarta3 | 2022-01-06
    driver.findElement(By.id("inputCarta3")).sendKeys("06/01/2022");
    Thread.sleep(2000);
    // 19 | click | css=.h2 | 
    driver.findElement(By.cssSelector(".h2")).click();
    Thread.sleep(2000);
    // 20 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    Thread.sleep(2000);
    // 21 | assertAlert | La carta di credito e scaduta | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("La carta di credito e' scaduta",str);
    Thread.sleep(2000);
  }
  
  
  @Test
  public void testProfiloErroreCVV() throws InterruptedException {
    // Test name: TestProfiloErroreCVV
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletloginfirst | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletloginfirst");
    Thread.sleep(2000);
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | name=email | 
    driver.findElement(By.name("email")).click();
    Thread.sleep(2000);
    // 4 | type | name=email | f.peluso25@gmail.com
    driver.findElement(By.name("email")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(2000);
    // 5 | click | name=password | 
    driver.findElement(By.name("password")).click();
    Thread.sleep(2000);
    // 6 | type | name=password | veloce123
    driver.findElement(By.name("password")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 7 | sendKeys | name=password | ${KEY_ENTER}
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    Thread.sleep(2000);
    // 8 | click | id=dropdownMenuButton | 
    driver.findElement(By.id("dropdownMenuButton")).click();
    Thread.sleep(2000);
    // 9 | click | linkText=Profilo | 
    driver.findElement(By.linkText("Profilo")).click();
    Thread.sleep(2000);
    // 10 | click | id=inputPassword1 | 
    driver.findElement(By.id("inputPassword1")).click();
    Thread.sleep(2000);
    // 11 | type | id=inputPassword1 | veloce1234
    driver.findElement(By.id("inputPassword1")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 12 | click | id=inputPassword2 | 
    driver.findElement(By.id("inputPassword2")).click();
    Thread.sleep(2000);
    // 13 | type | id=inputPassword2 | veloce1234
    driver.findElement(By.id("inputPassword2")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 14 | click | id=inputCarta1 | 
    driver.findElement(By.id("inputCarta1")).click();
    Thread.sleep(2000);
    // 15 | type | id=inputCarta1 | 1234567898989898
    driver.findElement(By.id("inputCarta1")).sendKeys("1234567898989898");
    Thread.sleep(2000);
    // 16 | click | id=inputCarta2 | 
    driver.findElement(By.id("inputCarta2")).click();
    Thread.sleep(2000);
    // 17 | type | id=inputCarta2 | 1234
    driver.findElement(By.id("inputCarta2")).sendKeys("1234");
    Thread.sleep(2000);
    // 18 | click | id=inputCarta3 | 
    driver.findElement(By.id("inputCarta3")).click();
    Thread.sleep(2000);
    // 19 | type | id=inputCarta3 | 2022-01-07
    driver.findElement(By.id("inputCarta3")).sendKeys("07/01/2022");
    Thread.sleep(2000);
    // 20 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    Thread.sleep(2000);
    // 21 | assertAlert | Hai inserito un cvv non valido | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("Hai inserito un cvv non valido",str);
    Thread.sleep(2000);
  }
  
  
  @Test
  public void testProfiloErroreSoloPWD() throws InterruptedException {
    // Test name: TestProfiloErroreSoloPWD
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletloginfirst | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletloginfirst");
    Thread.sleep(2000);
    // 2 | click | name=email | 
    driver.findElement(By.name("email")).click();
    Thread.sleep(2000);
    // 3 | type | name=email | f.peluso25@gmail.com
    driver.findElement(By.name("email")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(2000);
    // 4 | click | name=password | 
    driver.findElement(By.name("password")).click();
    Thread.sleep(2000);
    // 5 | type | name=password | veloce123
    driver.findElement(By.name("password")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 6 | sendKeys | name=password | ${KEY_ENTER}
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    Thread.sleep(2000);
    // 7 | click | id=dropdownMenuButton | 
    driver.findElement(By.id("dropdownMenuButton")).click();
    Thread.sleep(2000);
    // 8 | click | linkText=Profilo | 
    driver.findElement(By.linkText("Profilo")).click();
    Thread.sleep(2000);
    // 9 | click | id=inputPassword1 | 
    driver.findElement(By.id("inputPassword1")).click();
    Thread.sleep(2000);
    // 10 | type | id=inputPassword1 | v1
    driver.findElement(By.id("inputPassword1")).sendKeys("v1");
    Thread.sleep(2000);
    // 11 | click | id=inputPassword2 | 
    driver.findElement(By.id("inputPassword2")).click();
    Thread.sleep(2000);
    // 12 | type | id=inputPassword2 | v1
    driver.findElement(By.id("inputPassword2")).sendKeys("v1");
    Thread.sleep(2000);
    // 13 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    Thread.sleep(2000);
    // 14 | assertAlert | password non valida | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("password non valida",str);
    Thread.sleep(2000);
  }
  
  @Test
  public void testProfiloEseguitoSoloPWD() throws InterruptedException {
    // Test name: TestProfiloEseguitoSoloPWD
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletloginfirst |  | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletloginfirst");
    Thread.sleep(2000);
    // 2 | click | name=email |  | 
    driver.findElement(By.name("email")).click();
    Thread.sleep(2000);
    // 3 | type | name=email | f.peluso25@gmail.com | 
    driver.findElement(By.name("email")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(2000);
    // 4 | click | name=password |  | 
    driver.findElement(By.name("password")).click();
    Thread.sleep(2000);
    // 5 | type | name=password | veloce123 | 
    driver.findElement(By.name("password")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 6 | click | css=.invio |  | 
    driver.findElement(By.cssSelector(".invio")).click();
    Thread.sleep(2000);
    // 7 | click | id=dropdownMenuButton |  | 
    driver.findElement(By.id("dropdownMenuButton")).click();
    Thread.sleep(2000);
    // 8 | click | linkText=Profilo |  | 
    driver.findElement(By.linkText("Profilo")).click();
    Thread.sleep(2000);
    // 9 | click | id=inputPassword1 |  | 
    driver.findElement(By.id("inputPassword1")).click();
    Thread.sleep(2000);
    // 10 | type | id=inputPassword1 | veloce1234 | 
    driver.findElement(By.id("inputPassword1")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 11 | click | id=inputPassword2 |  | 
    driver.findElement(By.id("inputPassword2")).click();
    Thread.sleep(2000);
    // 12 | type | id=inputPassword2 | veloce1234 | 
    driver.findElement(By.id("inputPassword2")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 13 | click | css=.btn-primary |  | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    Thread.sleep(2000);
    // 14 | assertText | id=notifica | PASSWORD MODIFICATA! | 
    assertThat(driver.findElement(By.id("notifica")).getText(), is("PASSWORD MODIFICATA!"));
    Thread.sleep(2000);
  }
  
  
  @Test
  public void testProfiloEseguitoSoloCarta() throws InterruptedException {
    // Test name: TestProfiloEseguitoSoloCarta
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletloginfirst | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletloginfirst");
    Thread.sleep(2000);
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | name=email | 
    driver.findElement(By.name("email")).click();
    Thread.sleep(2000);
    // 4 | type | name=email | f.peluso25@gmail.com
    driver.findElement(By.name("email")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(2000);
    // 5 | click | name=password | 
    driver.findElement(By.name("password")).click();
    Thread.sleep(2000);
    // 6 | type | name=password | veloce123
    driver.findElement(By.name("password")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 7 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    Thread.sleep(2000);
    // 8 | click | css=.fa-user-astronaut | 
    driver.findElement(By.cssSelector(".fa-user-astronaut")).click();
    Thread.sleep(2000);
    // 9 | click | linkText=Profilo | 
    driver.findElement(By.linkText("Profilo")).click();
    Thread.sleep(2000);
    // 10 | click | id=inputCarta1 | 
    driver.findElement(By.id("inputCarta1")).click();
    Thread.sleep(2000);
    // 11 | type | id=inputCarta1 | 1234567898989898
    driver.findElement(By.id("inputCarta1")).sendKeys("1234567898989898");
    Thread.sleep(2000);
    // 12 | click | id=inputCarta2 | 
    driver.findElement(By.id("inputCarta2")).click();
    Thread.sleep(2000);
    // 13 | type | id=inputCarta2 | 123
    driver.findElement(By.id("inputCarta2")).sendKeys("123");
    Thread.sleep(2000);
    // 15 | type | id=inputCarta3 | 2022-02-05
    driver.findElement(By.id("inputCarta3")).sendKeys("05/02/2022");
    Thread.sleep(2000);
    // 16 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    Thread.sleep(2000);
    // 17 | assertText | name=codicecartaselenium | *****9898
    assertThat(driver.findElement(By.name("codicecartaselenium")).getText(), is("*****9898"));
  }
  
  
  @Test
  public void testProfiloErroreSoloCVV() throws InterruptedException {
    // Test name: TestProfiloErroreSoloCVV
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletloginfirst |  | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletloginfirst");
    Thread.sleep(2000);
    // 2 | setWindowSize | 1050x700 |  | 
   // driver.manage().window().setSize(new Dimension(1050, 700));
   // Thread.sleep(2000);
    // 3 | click | name=email |  | 
    driver.findElement(By.name("email")).click();
    Thread.sleep(2000);
    // 4 | type | name=email | f.peluso25@gmail.com | 
    driver.findElement(By.name("email")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(2000);
    // 5 | click | name=password |  | 
    driver.findElement(By.name("password")).click();
    Thread.sleep(2000);
    // 6 | type | name=password | veloce123 | 
    driver.findElement(By.name("password")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 7 | sendKeys | name=password | ${KEY_ENTER} | 
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    Thread.sleep(2000);
    // 8 | click | id=dropdownMenuButton |  | 
    driver.findElement(By.id("dropdownMenuButton")).click();
    Thread.sleep(2000);
    // 9 | click | linkText=Profilo |  | 
    driver.findElement(By.linkText("Profilo")).click();
    Thread.sleep(2000);
    // 10 | click | id=inputCarta1 |  | 
    driver.findElement(By.id("inputCarta1")).click();
    Thread.sleep(2000);
    // 11 | type | id=inputCarta1 | 1234567898989898 | 
    driver.findElement(By.id("inputCarta1")).sendKeys("1234567898989898");
    Thread.sleep(2000);
    // 12 | click | id=inputCarta2 |  | 
    driver.findElement(By.id("inputCarta2")).click();
    Thread.sleep(2000);
    // 13 | type | id=inputCarta2 | 1234 | 
    driver.findElement(By.id("inputCarta2")).sendKeys("1234");
    Thread.sleep(2000);
    // 14 | click | id=inputCarta3 |  | 
    //driver.findElement(By.id("inputCarta3")).click();
    Thread.sleep(2000);
    // 15 | type | id=inputCarta3 | 2022-01-07 | 
    driver.findElement(By.id("inputCarta3")).sendKeys("07/01/2022");
    Thread.sleep(2000);
    // 16 | click | css=.btn-primary |  | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    Thread.sleep(2000);
    // 17 | assertAlert | Hai inserito un cvv non valido |  | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("Hai inserito un cvv non valido",str);
    Thread.sleep(2000);
  }
  
  @Test
  public void testProfiloErroreSoloData() throws InterruptedException {
    // Test name: TestProfiloErroreSoloData
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletloginfirst | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletloginfirst");
    Thread.sleep(2000);
    // 2 | setWindowSize | 1050x700 | 
   // driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | name=email | 
    driver.findElement(By.name("email")).click();
    Thread.sleep(2000);
    // 4 | type | name=email | f.peluso25@gmail.com
    driver.findElement(By.name("email")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(2000);
    // 5 | click | name=password | 
    driver.findElement(By.name("password")).click();
    Thread.sleep(2000);
    // 6 | type | name=password | veloce123
    driver.findElement(By.name("password")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 7 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    Thread.sleep(2000);
    // 8 | click | css=.fa-user-astronaut | 
    driver.findElement(By.cssSelector(".fa-user-astronaut")).click();
    Thread.sleep(2000);
    // 9 | click | linkText=Profilo | 
    driver.findElement(By.linkText("Profilo")).click();
    Thread.sleep(2000);
    // 10 | click | id=inputCarta1 | 
    driver.findElement(By.id("inputCarta1")).click();
    Thread.sleep(2000);
    // 11 | type | id=inputCarta1 | 1234567898989898
    driver.findElement(By.id("inputCarta1")).sendKeys("1234567898989898");
    Thread.sleep(2000);
    // 12 | click | id=inputCarta2 | 
    driver.findElement(By.id("inputCarta2")).click();
    Thread.sleep(2000);
    // 13 | type | id=inputCarta2 | 123
    driver.findElement(By.id("inputCarta2")).sendKeys("123");
    Thread.sleep(2000);
    // 14 | click | id=inputCarta3 | 
    //driver.findElement(By.id("inputCarta3")).click();
    //Thread.sleep(2000);
    // 15 | type | id=inputCarta3 | 2022-01-07
    driver.findElement(By.id("inputCarta3")).sendKeys("07/01/2022");
    Thread.sleep(2000);
    // 16 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    Thread.sleep(2000);
    // 17 | assertAlert | La carta di credito e' scaduta | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("La carta di credito e' scaduta",str);
    Thread.sleep(2000);
  }
  
  
  @Test
  public void testProfiloErroreSoloCarta() throws InterruptedException {
    // Test name: TestProfiloErroreSoloData
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletloginfirst | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletloginfirst");
    Thread.sleep(2000);
    // 2 | setWindowSize | 1050x700 | 
   // driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | name=email | 
    driver.findElement(By.name("email")).click();
    Thread.sleep(2000);
    // 4 | type | name=email | f.peluso25@gmail.com
    driver.findElement(By.name("email")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(2000);
    // 5 | click | name=password | 
    driver.findElement(By.name("password")).click();
    Thread.sleep(2000);
    // 6 | type | name=password | veloce123
    driver.findElement(By.name("password")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 7 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    Thread.sleep(2000);
    // 8 | click | css=.fa-user-astronaut | 
    driver.findElement(By.cssSelector(".fa-user-astronaut")).click();
    Thread.sleep(2000);
    // 9 | click | linkText=Profilo | 
    driver.findElement(By.linkText("Profilo")).click();
    Thread.sleep(2000);
    // 10 | click | id=inputCarta1 | 
    driver.findElement(By.id("inputCarta1")).click();
    Thread.sleep(2000);
    // 11 | type | id=inputCarta1 | 1234567898989898
    driver.findElement(By.id("inputCarta1")).sendKeys("12345678989898989");
    Thread.sleep(2000);
    // 12 | click | id=inputCarta2 | 
    driver.findElement(By.id("inputCarta2")).click();
    Thread.sleep(2000);
    // 13 | type | id=inputCarta2 | 123
    driver.findElement(By.id("inputCarta2")).sendKeys("123");
    Thread.sleep(2000);
    // 14 | click | id=inputCarta3 | 
    //driver.findElement(By.id("inputCarta3")).click();
    //Thread.sleep(2000);
    // 15 | type | id=inputCarta3 | 2022-01-07
    driver.findElement(By.id("inputCarta3")).sendKeys("07/08/2023");
    Thread.sleep(2000);
    // 16 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    Thread.sleep(2000);
    // 17 | assertAlert | La carta di credito e' scaduta | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("Hai inserito una carta non valida",str);
    Thread.sleep(2000);
  }
  
  
}
