package profilosistema;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestLoginGestori {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "test/profilosistema/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testLoginFallitoPasswordOrdine() throws InterruptedException {
    // Test name: TestLoginFallitoPasswordOrdine
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletaccessoadmin | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletaccessoadmin");
    Thread.sleep(2000);
    // 2 | click | id=exampleInputEmail1 | 
    driver.findElement(By.id("exampleInputEmail1")).click();
    Thread.sleep(2000);
    // 3 | type | id=exampleInputEmail1 | ordine@admin.com
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("ordine@admin.com");
    Thread.sleep(2000);
    // 4 | click | id=exampleInputPassword1 | 
    driver.findElement(By.id("exampleInputPassword1")).click();
    Thread.sleep(2000);
    // 5 | type | id=exampleInputPassword1 | veloce1234
    driver.findElement(By.id("exampleInputPassword1")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 6 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
    Thread.sleep(2000);
    // 7 | assertText | name=messaggioerrore | Email/Password errata!
    assertThat(driver.findElement(By.name("messaggioerrore")).getText(), is("Email/Password errata!"));
  }
  @Test
  public void testLoginFallitoEntrambiGestori() throws InterruptedException {
    // Test name: TestLoginFallitoEntrambiGestori
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletaccessoadmin | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletaccessoadmin");
    Thread.sleep(2000);
    // 2 | click | id=exampleInputEmail1 | 
    driver.findElement(By.id("exampleInputEmail1")).click();
    Thread.sleep(2000);
    // 3 | type | id=exampleInputEmail1 | abc@gmail.com
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("abc@gmail.com");
    Thread.sleep(2000);
    // 4 | click | id=exampleInputPassword1 | 
    driver.findElement(By.id("exampleInputPassword1")).click();
    Thread.sleep(2000);
    // 5 | type | id=exampleInputPassword1 | veloce1234
    driver.findElement(By.id("exampleInputPassword1")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 6 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
    Thread.sleep(2000);
    // 7 | assertText | name=messaggioerrore | Email/Password errata!
    assertThat(driver.findElement(By.name("messaggioerrore")).getText(), is("Email/Password errata!"));
    Thread.sleep(2000);
  }
  @Test
  public void testLoginEseguitoOrdine() throws InterruptedException {
    // Test name: TestLoginEseguitoOrdine
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletaccessoadmin | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletaccessoadmin");
    Thread.sleep(2000);
    // 2 | click | id=exampleInputEmail1 | 
    driver.findElement(By.id("exampleInputEmail1")).click();
    Thread.sleep(2000);
    // 3 | type | id=exampleInputEmail1 | ordine@admin.com
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("ordine@admin.com");
    Thread.sleep(2000);
    // 4 | click | id=exampleInputPassword1 | 
    driver.findElement(By.id("exampleInputPassword1")).click();
    Thread.sleep(2000);
    // 5 | type | id=exampleInputPassword1 | veloce123
    driver.findElement(By.id("exampleInputPassword1")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 6 | sendKeys | id=exampleInputPassword1 | ${KEY_ENTER}
    driver.findElement(By.id("exampleInputPassword1")).sendKeys(Keys.ENTER);
    Thread.sleep(2000);
    // 7 | assertTitle | Ordini da gestire | 
    assertThat(driver.getTitle(), is("Ordini da gestire"));
    Thread.sleep(2000);
  }
  @Test
  public void testLoginFallitoPasswordProdotto() throws InterruptedException {
    // Test name: TestLoginFallitoPasswordProdotto
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletaccessoadmin | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletaccessoadmin");
    Thread.sleep(2000);
    // 2 | click | id=exampleInputEmail1 | 
    driver.findElement(By.id("exampleInputEmail1")).click();
    Thread.sleep(2000);
    // 3 | type | id=exampleInputEmail1 | prodotto@admin.com
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("prodotto@admin.com");
    Thread.sleep(2000);
    // 4 | click | id=exampleInputPassword1 | 
    driver.findElement(By.id("exampleInputPassword1")).click();
    Thread.sleep(2000);
    // 5 | type | id=exampleInputPassword1 | veloce1234
    driver.findElement(By.id("exampleInputPassword1")).sendKeys("veloce1234");
    Thread.sleep(2000);
    // 6 | click | css=.btn | 
    driver.findElement(By.cssSelector(".btn")).click();
    Thread.sleep(2000);
    // 7 | assertText | name=messaggioerrore | Email/Password errata!
    assertThat(driver.findElement(By.name("messaggioerrore")).getText(), is("Email/Password errata!"));
    Thread.sleep(2000);
  }
  @Test
  public void testLoginEseguitoProdotto() throws InterruptedException {
    // Test name: TestLoginEseguitoProdotto
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletaccessoadmin | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletaccessoadmin");
    Thread.sleep(2000);
    // 2 | click | id=exampleInputEmail1 | 
    driver.findElement(By.id("exampleInputEmail1")).click();
    Thread.sleep(2000);
    // 3 | type | id=exampleInputEmail1 | prodotto@admin.com
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("prodotto@admin.com");
    Thread.sleep(2000);
    // 4 | click | id=exampleInputPassword1 | 
    driver.findElement(By.id("exampleInputPassword1")).click();
    Thread.sleep(2000);
    // 5 | type | id=exampleInputPassword1 | veloce123
    driver.findElement(By.id("exampleInputPassword1")).sendKeys("veloce123");
    Thread.sleep(2000);
    // 6 | sendKeys | id=exampleInputPassword1 | ${KEY_ENTER}
    driver.findElement(By.id("exampleInputPassword1")).sendKeys(Keys.ENTER);
    Thread.sleep(2000);
    // 7 | assertTitle | Pagina-Amministrazione | 
    assertThat(driver.getTitle(), is("Pagina-Amministrazione"));
    Thread.sleep(2000);
  }
}
