package profilosistema;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestRegistrazione {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "test/profilosistema/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testRegistrazioneEseguito() throws InterruptedException {
    // Test name: TestRegistrazioneEseguito
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/ServletRegistrazione | 
    driver.get("http://localhost:8080/RAAF-GAMING/ServletRegistrazione");
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | id=validationCustom01 | 
    driver.findElement(By.id("validationCustom01")).click();
    // 4 | type | id=validationCustom01 | Francesco
    driver.findElement(By.id("validationCustom01")).sendKeys("Francesco");
    Thread.sleep(1000);
    // 5 | click | id=validationCustom02 | 
    driver.findElement(By.id("validationCustom02")).click();
    // 6 | type | id=validationCustom02 | Peluso
    driver.findElement(By.id("validationCustom02")).sendKeys("Peluso");
    Thread.sleep(1000);
    // 7 | click | id=datadinascita | 
   // driver.findElement(By.id("datadinascita")).click();
    // 8 | type | id=datadinascita | 2000-09-11
    driver.findElement(By.id("datadinascita")).sendKeys("11/09/2000");
    //Thread.sleep(2000);
    // 9 | click | id=validationCustom07 | 
    driver.findElement(By.id("validationCustom07")).click();
    // 10 | type | id=validationCustom07 | 8765432341234567
    driver.findElement(By.id("validationCustom07")).sendKeys("8765432341234567");
    Thread.sleep(1000);
    // 11 | click | id=data_scadenza | 
    //driver.findElement(By.id("data_scadenza")).click();
    // 12 | type | id=data_scadenza | 2022-02-16
    driver.findElement(By.id("data_scadenza")).sendKeys("16/02/2022");
    Thread.sleep(1000);
    // 13 | click | id=validationCustom08 | 
    driver.findElement(By.id("validationCustom08")).click();
    // 14 | type | id=validationCustom08 | 123
    driver.findElement(By.id("validationCustom08")).sendKeys("123");
    Thread.sleep(1000);
    // 15 | click | id=validationCustomUsername | 
    driver.findElement(By.id("validationCustomUsername")).click();
    // 16 | type | id=validationCustomUsername | peluso.francesco24@gmail.com
    driver.findElement(By.id("validationCustomUsername")).sendKeys("peluso.francesco24@gmail.com");
    Thread.sleep(1000);
    // 17 | click | id=validationCustom04 | 
    driver.findElement(By.id("validationCustom04")).click();
    // 18 | type | id=validationCustom04 | veloce123
    driver.findElement(By.id("validationCustom04")).sendKeys("veloce123");
    Thread.sleep(1000);
    // 19 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    // 20 | assertTitle | LOGIN | 
    assertThat(driver.getTitle(), is("LOGIN"));
    Thread.sleep(1000);
  }
  
  @Test
  public void testRegistrazioneErroreEmailEsistente() throws InterruptedException {
    // Test name: TestRegistrazioneErroreEmailEsistente
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/ServletRegistrazione | 
    driver.get("http://localhost:8080/RAAF-GAMING/ServletRegistrazione");
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | id=validationCustom01 | 
    driver.findElement(By.id("validationCustom01")).click();
    // 4 | type | id=validationCustom01 | Francesco
    driver.findElement(By.id("validationCustom01")).sendKeys("Francesco");
    Thread.sleep(1000);
    // 5 | click | id=validationCustom02 | 
    driver.findElement(By.id("validationCustom02")).click();
    // 6 | type | id=validationCustom02 | Peluso
    driver.findElement(By.id("validationCustom02")).sendKeys("Peluso");
    Thread.sleep(1000);
    // 7 | click | id=datadinascita | 
    //driver.findElement(By.id("datadinascita")).click();
    // 8 | type | id=datadinascita | 2000-09-11
    driver.findElement(By.id("datadinascita")).sendKeys("11/09/2000");
    // 9 | click | id=validationCustom07 | 
    driver.findElement(By.id("validationCustom07")).click();
    // 10 | type | id=validationCustom07 | 8765432341234567
    driver.findElement(By.id("validationCustom07")).sendKeys("8765432341234567");
    Thread.sleep(1000);
    // 11 | click | id=data_scadenza | 
    //driver.findElement(By.id("data_scadenza")).click();
    // 12 | type | id=data_scadenza | 2022-02-16
    driver.findElement(By.id("data_scadenza")).sendKeys("16/02/2022");
    Thread.sleep(1000);
    // 13 | click | id=validationCustom08 | 
    driver.findElement(By.id("validationCustom08")).click();
    // 14 | type | id=validationCustom08 | 123
    driver.findElement(By.id("validationCustom08")).sendKeys("123");
    Thread.sleep(1000);
    // 15 | click | id=validationCustomUsername | 
    driver.findElement(By.id("validationCustomUsername")).click();
    // 16 | type | id=validationCustomUsername | f.peluso25@gmail.com
    driver.findElement(By.id("validationCustomUsername")).sendKeys("f.peluso25@gmail.com");
    Thread.sleep(1000);
    // 17 | click | id=validationCustom04 | 
    driver.findElement(By.id("validationCustom04")).click();
    // 18 | type | id=validationCustom04 | veloce123
    driver.findElement(By.id("validationCustom04")).sendKeys("veloce123");
    Thread.sleep(1000);
    // 19 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    // 20 | assertText | name=messaggioerrore | Sei gia' iscritto al nostro sito!
    assertEquals("Sei gia' iscritto al nostro sito!",driver.findElement(By.name("messaggioerrore")).getText());
    Thread.sleep(1000);
  }
  
  
  @Test
  public void testRegistrazioneErroreCartaEsistente() throws InterruptedException {
    // Test name: TestRegistrazioneErroreEmailEsistente
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/ServletRegistrazione | 
    driver.get("http://localhost:8080/RAAF-GAMING/ServletRegistrazione");
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | id=validationCustom01 | 
    driver.findElement(By.id("validationCustom01")).click();
    // 4 | type | id=validationCustom01 | Francesco
    driver.findElement(By.id("validationCustom01")).sendKeys("Francesco");
    Thread.sleep(1000);
    // 5 | click | id=validationCustom02 | 
    driver.findElement(By.id("validationCustom02")).click();
    // 6 | type | id=validationCustom02 | Peluso
    driver.findElement(By.id("validationCustom02")).sendKeys("Peluso");
    Thread.sleep(1000);
    // 7 | click | id=datadinascita | 
    //driver.findElement(By.id("datadinascita")).click();
    // 8 | type | id=datadinascita | 2000-09-11
    driver.findElement(By.id("datadinascita")).sendKeys("11/09/2000");
    // 9 | click | id=validationCustom07 | 
    driver.findElement(By.id("validationCustom07")).click();
    // 10 | type | id=validationCustom07 | 8765432341234567
    driver.findElement(By.id("validationCustom07")).sendKeys("1234567891234567");
    Thread.sleep(1000);
    // 11 | click | id=data_scadenza | 
    //driver.findElement(By.id("data_scadenza")).click();
    // 12 | type | id=data_scadenza | 2022-02-16
    driver.findElement(By.id("data_scadenza")).sendKeys("16/02/2022");
    Thread.sleep(1000);
    // 13 | click | id=validationCustom08 | 
    driver.findElement(By.id("validationCustom08")).click();
    // 14 | type | id=validationCustom08 | 123
    driver.findElement(By.id("validationCustom08")).sendKeys("123");
    Thread.sleep(1000);
    // 15 | click | id=validationCustomUsername | 
    driver.findElement(By.id("validationCustomUsername")).click();
    // 16 | type | id=validationCustomUsername | f.peluso25@gmail.com
    driver.findElement(By.id("validationCustomUsername")).sendKeys("peluso.francesco24@gmail.com");
    Thread.sleep(1000);
    // 17 | click | id=validationCustom04 | 
    driver.findElement(By.id("validationCustom04")).click();
    // 18 | type | id=validationCustom04 | veloce123
    driver.findElement(By.id("validationCustom04")).sendKeys("veloce123");
    Thread.sleep(1000);
    // 19 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    // 20 | assertText | name=messaggioerrore | Sei gia' iscritto al nostro sito!
    assertEquals("Non puoi registrarti con questa carta",driver.findElement(By.name("messaggioerrore")).getText());
    Thread.sleep(1000);
  }
  
  @Test
  public void testRegistrazioneErroreNome() throws InterruptedException {
    // Test name: TestRegistrazioneEseguito
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/ServletRegistrazione | 
    driver.get("http://localhost:8080/RAAF-GAMING/ServletRegistrazione");
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | id=validationCustom01 | 
    driver.findElement(By.id("validationCustom01")).click();
    // 4 | type | id=validationCustom01 | Francesco
    driver.findElement(By.id("validationCustom01")).sendKeys("");
    Thread.sleep(1000);
    // 5 | click | id=validationCustom02 | 
    driver.findElement(By.id("validationCustom02")).click();
    // 6 | type | id=validationCustom02 | Peluso
    driver.findElement(By.id("validationCustom02")).sendKeys("Peluso");
    Thread.sleep(1000);
    // 7 | click | id=datadinascita | 
   // driver.findElement(By.id("datadinascita")).click();
    // 8 | type | id=datadinascita | 2000-09-11
    driver.findElement(By.id("datadinascita")).sendKeys("11/09/2000");
    //Thread.sleep(2000);
    // 9 | click | id=validationCustom07 | 
    driver.findElement(By.id("validationCustom07")).click();
    // 10 | type | id=validationCustom07 | 8765432341234567
    driver.findElement(By.id("validationCustom07")).sendKeys("8765432341234567");
    Thread.sleep(1000);
    // 11 | click | id=data_scadenza | 
    //driver.findElement(By.id("data_scadenza")).click();
    // 12 | type | id=data_scadenza | 2022-02-16
    driver.findElement(By.id("data_scadenza")).sendKeys("16/02/2022");
    Thread.sleep(1000);
    // 13 | click | id=validationCustom08 | 
    driver.findElement(By.id("validationCustom08")).click();
    // 14 | type | id=validationCustom08 | 123
    driver.findElement(By.id("validationCustom08")).sendKeys("123");
    Thread.sleep(1000);
    // 15 | click | id=validationCustomUsername | 
    driver.findElement(By.id("validationCustomUsername")).click();
    // 16 | type | id=validationCustomUsername | peluso.francesco24@gmail.com
    driver.findElement(By.id("validationCustomUsername")).sendKeys("peluso.francesco24@gmail.com");
    Thread.sleep(1000);
    // 17 | click | id=validationCustom04 | 
    driver.findElement(By.id("validationCustom04")).click();
    // 18 | type | id=validationCustom04 | veloce123
    driver.findElement(By.id("validationCustom04")).sendKeys("veloce123");
    Thread.sleep(1000);
    // 19 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    // 20 | assertalert | LOGIN | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("Hai inserito un nome non valido",str);
    Thread.sleep(1000);
  }
  
  @Test
  public void testRegistrazioneErroreCognome() throws InterruptedException {
    // Test name: TestRegistrazioneEseguito
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/ServletRegistrazione | 
    driver.get("http://localhost:8080/RAAF-GAMING/ServletRegistrazione");
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | id=validationCustom01 | 
    driver.findElement(By.id("validationCustom01")).click();
    // 4 | type | id=validationCustom01 | Francesco
    driver.findElement(By.id("validationCustom01")).sendKeys("Francesco");
    Thread.sleep(1000);
    // 5 | click | id=validationCustom02 | 
    driver.findElement(By.id("validationCustom02")).click();
    // 6 | type | id=validationCustom02 | Peluso
    driver.findElement(By.id("validationCustom02")).sendKeys("");
    Thread.sleep(1000);
    // 7 | click | id=datadinascita | 
   // driver.findElement(By.id("datadinascita")).click();
    // 8 | type | id=datadinascita | 2000-09-11
    driver.findElement(By.id("datadinascita")).sendKeys("11/09/2000");
    //Thread.sleep(2000);
    // 9 | click | id=validationCustom07 | 
    driver.findElement(By.id("validationCustom07")).click();
    // 10 | type | id=validationCustom07 | 8765432341234567
    driver.findElement(By.id("validationCustom07")).sendKeys("8765432341234567");
    Thread.sleep(1000);
    // 11 | click | id=data_scadenza | 
    //driver.findElement(By.id("data_scadenza")).click();
    // 12 | type | id=data_scadenza | 2022-02-16
    driver.findElement(By.id("data_scadenza")).sendKeys("16/02/2022");
    Thread.sleep(1000);
    // 13 | click | id=validationCustom08 | 
    driver.findElement(By.id("validationCustom08")).click();
    // 14 | type | id=validationCustom08 | 123
    driver.findElement(By.id("validationCustom08")).sendKeys("123");
    Thread.sleep(1000);
    // 15 | click | id=validationCustomUsername | 
    driver.findElement(By.id("validationCustomUsername")).click();
    // 16 | type | id=validationCustomUsername | peluso.francesco24@gmail.com
    driver.findElement(By.id("validationCustomUsername")).sendKeys("peluso.francesco24@gmail.com");
    Thread.sleep(1000);
    // 17 | click | id=validationCustom04 | 
    driver.findElement(By.id("validationCustom04")).click();
    // 18 | type | id=validationCustom04 | veloce123
    driver.findElement(By.id("validationCustom04")).sendKeys("veloce123");
    Thread.sleep(1000);
    // 19 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    // 20 | assertalert | LOGIN | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("Hai inserito un cognome non valido",str);
    Thread.sleep(1000);
  }
  
  @Test
  public void testRegistrazioneErroreEta() throws InterruptedException {
    // Test name: TestRegistrazioneEseguito
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/ServletRegistrazione | 
    driver.get("http://localhost:8080/RAAF-GAMING/ServletRegistrazione");
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | id=validationCustom01 | 
    driver.findElement(By.id("validationCustom01")).click();
    // 4 | type | id=validationCustom01 | Francesco
    driver.findElement(By.id("validationCustom01")).sendKeys("Francesco");
    Thread.sleep(1000);
    // 5 | click | id=validationCustom02 | 
    driver.findElement(By.id("validationCustom02")).click();
    // 6 | type | id=validationCustom02 | Peluso
    driver.findElement(By.id("validationCustom02")).sendKeys("Peluso");
    Thread.sleep(1000);
    // 7 | click | id=datadinascita | 
   // driver.findElement(By.id("datadinascita")).click();
    // 8 | type | id=datadinascita | 2000-09-11
    driver.findElement(By.id("datadinascita")).sendKeys("11/09/2020");
    //Thread.sleep(2000);
    // 9 | click | id=validationCustom07 | 
    driver.findElement(By.id("validationCustom07")).click();
    // 10 | type | id=validationCustom07 | 8765432341234567
    driver.findElement(By.id("validationCustom07")).sendKeys("8765432341234567");
    Thread.sleep(1000);
    // 11 | click | id=data_scadenza | 
    //driver.findElement(By.id("data_scadenza")).click();
    // 12 | type | id=data_scadenza | 2022-02-16
    driver.findElement(By.id("data_scadenza")).sendKeys("16/02/2022");
    Thread.sleep(1000);
    // 13 | click | id=validationCustom08 | 
    driver.findElement(By.id("validationCustom08")).click();
    // 14 | type | id=validationCustom08 | 123
    driver.findElement(By.id("validationCustom08")).sendKeys("123");
    Thread.sleep(1000);
    // 15 | click | id=validationCustomUsername | 
    driver.findElement(By.id("validationCustomUsername")).click();
    // 16 | type | id=validationCustomUsername | peluso.francesco24@gmail.com
    driver.findElement(By.id("validationCustomUsername")).sendKeys("peluso.francesco24@gmail.com");
    Thread.sleep(1000);
    // 17 | click | id=validationCustom04 | 
    driver.findElement(By.id("validationCustom04")).click();
    // 18 | type | id=validationCustom04 | veloce123
    driver.findElement(By.id("validationCustom04")).sendKeys("veloce123");
    Thread.sleep(1000);
    // 19 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    // 20 | assertalert | LOGIN | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("Non hai l'età per registrarti!",str);
    Thread.sleep(1000);
  }
  
  @Test
  public void testRegistrazioneErroreCarta() throws InterruptedException {
    // Test name: TestRegistrazioneEseguito
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/ServletRegistrazione | 
    driver.get("http://localhost:8080/RAAF-GAMING/ServletRegistrazione");
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | id=validationCustom01 | 
    driver.findElement(By.id("validationCustom01")).click();
    // 4 | type | id=validationCustom01 | Francesco
    driver.findElement(By.id("validationCustom01")).sendKeys("Francesco");
    Thread.sleep(1000);
    // 5 | click | id=validationCustom02 | 
    driver.findElement(By.id("validationCustom02")).click();
    // 6 | type | id=validationCustom02 | Peluso
    driver.findElement(By.id("validationCustom02")).sendKeys("Peluso");
    Thread.sleep(1000);
    // 7 | click | id=datadinascita | 
   // driver.findElement(By.id("datadinascita")).click();
    // 8 | type | id=datadinascita | 2000-09-11
    driver.findElement(By.id("datadinascita")).sendKeys("11/09/2000");
    //Thread.sleep(2000);
    // 9 | click | id=validationCustom07 | 
    driver.findElement(By.id("validationCustom07")).click();
    // 10 | type | id=validationCustom07 | 8765432341234567
    driver.findElement(By.id("validationCustom07")).sendKeys("8765b4323a234567");
    Thread.sleep(1000);
    // 11 | click | id=data_scadenza | 
    //driver.findElement(By.id("data_scadenza")).click();
    // 12 | type | id=data_scadenza | 2022-02-16
    driver.findElement(By.id("data_scadenza")).sendKeys("16/02/2022");
    Thread.sleep(1000);
    // 13 | click | id=validationCustom08 | 
    driver.findElement(By.id("validationCustom08")).click();
    // 14 | type | id=validationCustom08 | 123
    driver.findElement(By.id("validationCustom08")).sendKeys("123");
    Thread.sleep(1000);
    // 15 | click | id=validationCustomUsername | 
    driver.findElement(By.id("validationCustomUsername")).click();
    // 16 | type | id=validationCustomUsername | peluso.francesco24@gmail.com
    driver.findElement(By.id("validationCustomUsername")).sendKeys("peluso.francesco24@gmail.com");
    Thread.sleep(1000);
    // 17 | click | id=validationCustom04 | 
    driver.findElement(By.id("validationCustom04")).click();
    // 18 | type | id=validationCustom04 | veloce123
    driver.findElement(By.id("validationCustom04")).sendKeys("veloce123");
    Thread.sleep(1000);
    // 19 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    // 20 | assertalert | LOGIN | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("Hai inserito un codice carta non valida",str);
    Thread.sleep(1000);
  }
  
  @Test
  public void testRegistrazioneErroreDataScadenza() throws InterruptedException {
    // Test name: TestRegistrazioneEseguito
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/ServletRegistrazione | 
    driver.get("http://localhost:8080/RAAF-GAMING/ServletRegistrazione");
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | id=validationCustom01 | 
    driver.findElement(By.id("validationCustom01")).click();
    // 4 | type | id=validationCustom01 | Francesco
    driver.findElement(By.id("validationCustom01")).sendKeys("Francesco");
    Thread.sleep(1000);
    // 5 | click | id=validationCustom02 | 
    driver.findElement(By.id("validationCustom02")).click();
    // 6 | type | id=validationCustom02 | Peluso
    driver.findElement(By.id("validationCustom02")).sendKeys("Peluso");
    Thread.sleep(1000);
    // 7 | click | id=datadinascita | 
   // driver.findElement(By.id("datadinascita")).click();
    // 8 | type | id=datadinascita | 2000-09-11
    driver.findElement(By.id("datadinascita")).sendKeys("11/09/2000");
    //Thread.sleep(2000);
    // 9 | click | id=validationCustom07 | 
    driver.findElement(By.id("validationCustom07")).click();
    // 10 | type | id=validationCustom07 | 8765432341234567
    driver.findElement(By.id("validationCustom07")).sendKeys("8765432341234567");
    Thread.sleep(1000);
    // 11 | click | id=data_scadenza | 
    //driver.findElement(By.id("data_scadenza")).click();
    // 12 | type | id=data_scadenza | 2022-02-16
    driver.findElement(By.id("data_scadenza")).sendKeys("8/01/2022");
    Thread.sleep(1000);
    // 13 | click | id=validationCustom08 | 
    driver.findElement(By.id("validationCustom08")).click();
    // 14 | type | id=validationCustom08 | 123
    driver.findElement(By.id("validationCustom08")).sendKeys("123");
    Thread.sleep(1000);
    // 15 | click | id=validationCustomUsername | 
    driver.findElement(By.id("validationCustomUsername")).click();
    // 16 | type | id=validationCustomUsername | peluso.francesco24@gmail.com
    driver.findElement(By.id("validationCustomUsername")).sendKeys("peluso.francesco24@gmail.com");
    Thread.sleep(1000);
    // 17 | click | id=validationCustom04 | 
    driver.findElement(By.id("validationCustom04")).click();
    // 18 | type | id=validationCustom04 | veloce123
    driver.findElement(By.id("validationCustom04")).sendKeys("veloce123");
    Thread.sleep(1000);
    // 19 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    // 20 | assertalert | LOGIN | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("Data scadenza non valida",str);
    Thread.sleep(1000);
  }
  
  
  @Test
  public void testRegistrazioneErroreCVV() throws InterruptedException {
    // Test name: TestRegistrazioneEseguito
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/ServletRegistrazione | 
    driver.get("http://localhost:8080/RAAF-GAMING/ServletRegistrazione");
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | id=validationCustom01 | 
    driver.findElement(By.id("validationCustom01")).click();
    // 4 | type | id=validationCustom01 | Francesco
    driver.findElement(By.id("validationCustom01")).sendKeys("Francesco");
    Thread.sleep(1000);
    // 5 | click | id=validationCustom02 | 
    driver.findElement(By.id("validationCustom02")).click();
    // 6 | type | id=validationCustom02 | Peluso
    driver.findElement(By.id("validationCustom02")).sendKeys("Peluso");
    Thread.sleep(1000);
    // 7 | click | id=datadinascita | 
   // driver.findElement(By.id("datadinascita")).click();
    // 8 | type | id=datadinascita | 2000-09-11
    driver.findElement(By.id("datadinascita")).sendKeys("11/09/2000");
    //Thread.sleep(2000);
    // 9 | click | id=validationCustom07 | 
    driver.findElement(By.id("validationCustom07")).click();
    // 10 | type | id=validationCustom07 | 8765432341234567
    driver.findElement(By.id("validationCustom07")).sendKeys("8765432341234567");
    Thread.sleep(1000);
    // 11 | click | id=data_scadenza | 
    //driver.findElement(By.id("data_scadenza")).click();
    // 12 | type | id=data_scadenza | 2022-02-16
    driver.findElement(By.id("data_scadenza")).sendKeys("16/02/2022");
    Thread.sleep(1000);
    // 13 | click | id=validationCustom08 | 
    driver.findElement(By.id("validationCustom08")).click();
    // 14 | type | id=validationCustom08 | 123
    driver.findElement(By.id("validationCustom08")).sendKeys("12a");
    Thread.sleep(1000);
    // 15 | click | id=validationCustomUsername | 
    driver.findElement(By.id("validationCustomUsername")).click();
    // 16 | type | id=validationCustomUsername | peluso.francesco24@gmail.com
    driver.findElement(By.id("validationCustomUsername")).sendKeys("peluso.francesco24@gmail.com");
    Thread.sleep(1000);
    // 17 | click | id=validationCustom04 | 
    driver.findElement(By.id("validationCustom04")).click();
    // 18 | type | id=validationCustom04 | veloce123
    driver.findElement(By.id("validationCustom04")).sendKeys("veloce123");
    Thread.sleep(1000);
    // 19 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    // 20 | assertalert | LOGIN | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("Hai inserito un CVV non valido",str);
    Thread.sleep(1000);
  }
  
  
  @Test
  public void testRegistrazioneErroreEmail() throws InterruptedException {
    // Test name: TestRegistrazioneEseguito
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/ServletRegistrazione | 
    driver.get("http://localhost:8080/RAAF-GAMING/ServletRegistrazione");
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | id=validationCustom01 | 
    driver.findElement(By.id("validationCustom01")).click();
    // 4 | type | id=validationCustom01 | Francesco
    driver.findElement(By.id("validationCustom01")).sendKeys("Francesco");
    Thread.sleep(1000);
    // 5 | click | id=validationCustom02 | 
    driver.findElement(By.id("validationCustom02")).click();
    // 6 | type | id=validationCustom02 | Peluso
    driver.findElement(By.id("validationCustom02")).sendKeys("Peluso");
    Thread.sleep(1000);
    // 7 | click | id=datadinascita | 
   // driver.findElement(By.id("datadinascita")).click();
    // 8 | type | id=datadinascita | 2000-09-11
    driver.findElement(By.id("datadinascita")).sendKeys("11/09/2000");
    //Thread.sleep(2000);
    // 9 | click | id=validationCustom07 | 
    driver.findElement(By.id("validationCustom07")).click();
    // 10 | type | id=validationCustom07 | 8765432341234567
    driver.findElement(By.id("validationCustom07")).sendKeys("8765432341234567");
    Thread.sleep(1000);
    // 11 | click | id=data_scadenza | 
    //driver.findElement(By.id("data_scadenza")).click();
    // 12 | type | id=data_scadenza | 2022-02-16
    driver.findElement(By.id("data_scadenza")).sendKeys("16/02/2022");
    Thread.sleep(1000);
    // 13 | click | id=validationCustom08 | 
    driver.findElement(By.id("validationCustom08")).click();
    // 14 | type | id=validationCustom08 | 123
    driver.findElement(By.id("validationCustom08")).sendKeys("123");
    Thread.sleep(1000);
    // 15 | click | id=validationCustomUsername | 
    driver.findElement(By.id("validationCustomUsername")).click();
    // 16 | type | id=validationCustomUsername | peluso.francesco24@gmail.com
    driver.findElement(By.id("validationCustomUsername")).sendKeys("abc.com");
    Thread.sleep(1000);
    // 17 | click | id=validationCustom04 | 
    driver.findElement(By.id("validationCustom04")).click();
    // 18 | type | id=validationCustom04 | veloce123
    driver.findElement(By.id("validationCustom04")).sendKeys("veloce123");
    Thread.sleep(1000);
    // 19 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    // 20 | assertalert | LOGIN | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("Hai inserito un'email errata",str);
    Thread.sleep(1000);
  }
  
  @Test
  public void testRegistrazioneErrorePassword() throws InterruptedException {
    // Test name: TestRegistrazioneEseguito
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/ServletRegistrazione | 
    driver.get("http://localhost:8080/RAAF-GAMING/ServletRegistrazione");
    // 2 | setWindowSize | 1050x700 | 
    //driver.manage().window().setSize(new Dimension(1050, 700));
    // 3 | click | id=validationCustom01 | 
    driver.findElement(By.id("validationCustom01")).click();
    // 4 | type | id=validationCustom01 | Francesco
    driver.findElement(By.id("validationCustom01")).sendKeys("Francesco");
    Thread.sleep(1000);
    // 5 | click | id=validationCustom02 | 
    driver.findElement(By.id("validationCustom02")).click();
    // 6 | type | id=validationCustom02 | Peluso
    driver.findElement(By.id("validationCustom02")).sendKeys("Peluso");
    Thread.sleep(1000);
    // 7 | click | id=datadinascita | 
   // driver.findElement(By.id("datadinascita")).click();
    // 8 | type | id=datadinascita | 2000-09-11
    driver.findElement(By.id("datadinascita")).sendKeys("11/09/2000");
    //Thread.sleep(2000);
    // 9 | click | id=validationCustom07 | 
    driver.findElement(By.id("validationCustom07")).click();
    // 10 | type | id=validationCustom07 | 8765432341234567
    driver.findElement(By.id("validationCustom07")).sendKeys("8765432341234567");
    Thread.sleep(1000);
    // 11 | click | id=data_scadenza | 
    //driver.findElement(By.id("data_scadenza")).click();
    // 12 | type | id=data_scadenza | 2022-02-16
    driver.findElement(By.id("data_scadenza")).sendKeys("16/02/2022");
    Thread.sleep(1000);
    // 13 | click | id=validationCustom08 | 
    driver.findElement(By.id("validationCustom08")).click();
    // 14 | type | id=validationCustom08 | 123
    driver.findElement(By.id("validationCustom08")).sendKeys("123");
    Thread.sleep(1000);
    // 15 | click | id=validationCustomUsername | 
    driver.findElement(By.id("validationCustomUsername")).click();
    // 16 | type | id=validationCustomUsername | peluso.francesco24@gmail.com
    driver.findElement(By.id("validationCustomUsername")).sendKeys("peluso.francesco24@gmail.com");
    Thread.sleep(1000);
    // 17 | click | id=validationCustom04 | 
    driver.findElement(By.id("validationCustom04")).click();
    // 18 | type | id=validationCustom04 | veloce123
    driver.findElement(By.id("validationCustom04")).sendKeys("");
    Thread.sleep(1000);
    // 19 | click | css=.invio | 
    driver.findElement(By.cssSelector(".invio")).click();
    // 20 | assertalert | LOGIN | 
    Alert alert = driver.switchTo().alert();
    String str = alert.getText();
    assertEquals("Hai inserito una password errata",str);
    Thread.sleep(1000);
  }
  
}
