package acquistosistema;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.junit.Assert;

import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestVisualizzaCarrello {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "test/acquistosistema/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void testVisualizzaCarelloCarrelloVuoto() throws InterruptedException {
    // Test name: TestVisualizzaCarello_CarrelloVuoto
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/ | 
    driver.get("http://localhost:8080/RAAF-GAMING/");
    // 2 | click | id=sostituisciCarrello | 
    Thread.sleep(5000);
    driver.findElement(By.id("sostituisciCarrello")).click();
    // 3 | assertTitle | CARRELLO | 
    assertThat(driver.getTitle(), is("CARRELLO"));
    Thread.sleep(5000);
    // 4 | assertText | name=NonHaiProdotti | NON HAI NESSUN PRODOTTO NEL CARRELLO!
    assertThat(driver.findElement(By.name("NonHaiProdotti")).getText(), is("NON HAI NESSUN PRODOTTO NEL CARRELLO!"));
  }
  
  @Test
  public void testVisualizzaCarelloCarrelloConElementi() throws InterruptedException {
    // Test name: TestVisualizzaCarello_CarrelloConElementi
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletprodotto?id=1 | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletprodotto?id=1");
    // 2 | click | css=.pl-2 
    Thread.sleep(5000);
    driver.findElement(By.cssSelector(".pl-2")).click();
    Thread.sleep(5000);
    // 3 | assertAlert | Aggiunta nel carrello fatta con successo! | 
    Alert alert=driver.switchTo().alert();
    String s= alert.getText();
    if(s.equals("Aggiunta nel carrello fatta con successo!"))
    {
    	alert.accept();
    	Thread.sleep(5000);
    	// 4 | click | id=sostituisciCarrello | 
        driver.findElement(By.id("sostituisciCarrello")).click();
        Thread.sleep(5000);
        // 5 | assertNotText | name=NonHaiProdotti | NON HAI NESSUN PRODOTTO NEL CARRELLO!
        List<WebElement> list = driver.findElements(By.name("NonHaiProdotti"));
        Assert.assertTrue("NON HAI NESSUN PRODOTTO NEL CARRELLO!", list.size() == 0);
        //assertThat(driver.findElement(By.name("NonHaiProdotti")).getText(), is(not("NON HAI NESSUN PRODOTTO NEL CARRELLO!")));
    }
  }
  
}
