package acquistosistema;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestEliminazioneProdotto {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "test/acquistosistema/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testEliminazioneProdottiFallito() {
    // Test name: TestEliminazioneProdotti_Fallito
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletcarrello | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletcarrello");
    // 2 | assertText | name=NonHaiProdotti | NON HAI NESSUN PRODOTTO NEL CARRELLO!
    assertThat(driver.findElement(By.name("NonHaiProdotti")).getText(), is("NON HAI NESSUN PRODOTTO NEL CARRELLO!"));
  }
  @Test
  public void testliminazioneProdottoRiuscito() throws InterruptedException {
    // Test name: TestliminazioneProdotto_Riuscito
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletprodotto?id=1 | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletprodotto?id=1");
    // 2 | click | css=.pl-2 | 
    driver.findElement(By.cssSelector(".pl-2")).click();
    // 3 | assertAlert | Aggiunta nel carrello fatta con successo! |
    Thread.sleep(5000);
    Alert alert=driver.switchTo().alert();
    String text= alert.getText();
    if(text.equals("Aggiunta nel carrello fatta con successo!"))
    {
    	alert.accept();
    }
    // 4 | click | id=sostituisciCarrello | 
    Thread.sleep(5000);
    driver.findElement(By.id("sostituisciCarrello")).click();
    // 5 | click | id=quantity |
    Thread.sleep(5000);
    driver.findElement(By.id("quantity")).click();
    // 6 | assertText | name=NonHaiProdotti | NON HAI NESSUN PRODOTTO NEL CARRELLO!
    assertThat(driver.findElement(By.name("NonHaiProdotti")).getText(), is("NON HAI NESSUN PRODOTTO NEL CARRELLO!"));
  }
  /*@Test
  public void testEliminazioneProdottoRiuscita() {
    // Test name: TestEliminazioneProdotto_Riuscita
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/RAAF-GAMING/servletcarrello | 
    driver.get("http://localhost:8080/RAAF-GAMING/servletcarrello");
    // 2 | click | id=quantity | 
    driver.findElement(By.id("quantity")).click();
    // 3 | assertText | name=NonHaiProdotti | NON HAI NESSUN PRODOTTO NEL CARRELLO!
    assertThat(driver.findElement(By.name("NonHaiProdotti")).getText(), is("NON HAI NESSUN PRODOTTO NEL CARRELLO!"));
  }*/
}
